### ISSUE TITLE
How to deploy to external tomcat as .war file?

### ISSUE THREAD

**Issue by hpardess** [swathisprasad/spring-boot-angular6-maven-project#1]
I have setup this repository. I can run the application but how to deploy the project to an external tomcat server as .war file?

I tried following command to package but the js libraries are not accessible (404)
```
/mvn clean install
tutorial-server/mvn clean dependency:copy-dependencies package
```

if I run only` tutorial-server/mvn spring-boot:run` then the application is running perfectly.

Is there any other best way to deploy the application in production server?

Regards,
HPardess

**Comment by swathisprasad** [comment]
@hpardess  the command _mvn clean install_ will generate the war file which will package angular resources as well. The _maven-resources-plugin_ in tutorial-server/pom.xml does the task of copying resources. 

the command _mvn clean install_ should be executed on root directory _tutorial-parent/_

**Comment by littleOStar** [comment]
https://stackoverflow.com/questions/39468479/angular-html5mode-in-tomcat-apache-8-5-4-gives-404-on-page-refresh
https://stackoverflow.com/questions/51042875/url-rewriting-angular-4-on-tomcat-8-server

it's working.

1. build angular, get static html. put angular app on javaee maven-archetype-webapp webapp folder.
2. maven clean package get xxx.war.
3. use above stackoverflow post, setting tomcat.
4. finish.

**Comment by nts27** [comment]
I am getting the war file with all angular resources, and keeping it in webapps folder, server is staring up.
When I hit the url - "http://localhost:8080/app-name", it says 404 error.

Please help how to deploy in tomcat
