### ISSUE TITLE
Why does the app have a login page?  

### ISSUE THREAD

**Issue by dhoffer** [swathisprasad/spring-boot-angular6-maven-project#2]
I'm new to Angular (not new to Java), when I run the app either as a standalone Spring Boot app or when I deploy the war to my Tomcat the app presents with a user login page.  Where is this coming from?  I don't see that in your front end code.  What is the login?
In your example/tutorial I'd like to see explanation of how the front-end works so I can know how to modify it to present what I need in my web app.

**Comment by littleOStar** [comment]
from https://dzone.com/articles/building-a-web-app-using-spring-boot-angular-6-and --> comment

Swathi Prasad  littleOStar - 13/1/2019 

It comes from spring boot starter security plugin. The user name is user and password is the generated one in console on server startup.

**Comment by swathisprasad** [comment]
No fix is needed.
