### ISSUE TITLE
Deploy the server war file to external tomcat

### ISSUE THREAD

**Issue by nts27** [swathisprasad/spring-boot-angular6-maven-project#5]
I am getting the war file from the server module target folder with all angular resources, and keeping it in webapps folder in tomcat, server is starting up.
When I hit the url - "http://localhost:8080/app-name", it says 404 error.

and When I hit the url = "http://localhost:8080/" - it opens the tomcat html

Please help how to deploy in tomcat

**Comment by swathisprasad** [comment]
@nts27 The "app-name" in your URL "http://localhost:8080/app-name" should be spring boot war file name. war file name is the tomcat context path name and that has to be used to access the application. Is that how you have deployed?

**Comment by nts27** [comment]
@swathisprasad Yes I was mentioning the app name,w ar file name. The problem was I was deploying spring boot 2 application in tomcat 7, however tomcat 8 should be used. Hence now its deployed.
Cheers
